-- 標準のターミナルバッファを使用するため、toggletermを無効化
return {}

-- return {
--   "akinsho/toggleterm.nvim",
--   version = "*",
--   init = function()
--     -- Neovim起動の早い段階でシェル設定を行う
--     if vim.fn.has("win32") == 1 then
--       vim.o.shell = '"C:/Program Files/Git/bin/bash.exe"'
--       vim.o.shellcmdflag = "-c"
--       vim.o.shellpipe = "2>&1| tee"
--       vim.o.shellquote = ""
--       vim.o.shellxquote = ""
--     end
--   end,
--   config = function()
--     require("toggleterm").setup({
--       size = 20,
--       open_mapping = [[<C-t>]],
--       hide_numbers = true,
--       shade_terminals = false,
--       start_in_insert = true,
--       insert_mappings = true,
--       terminal_mappings = true,
--       persist_size = true,
--       direction = "float",
--       close_on_exit = true,
--       float_opts = {
--         border = "single",
--         winblend = 0,
--         width = function()
--           return math.floor(vim.o.columns * 0.9)
--         end,
--         height = function()
--           return math.floor(vim.o.lines * 0.8)
--         end,
--       },
--     })
--
--     vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#00ff00", bg = "NONE", bold = true })
--   end,
-- }
